#! /bin/bash

if [ "$#" != 2 ]; then
  echo "usage: $0 sub-folder result-folder"
  exit 1
fi

for f in "$1"/*/; do
  name=$(basename "$f")
  echo "+++++++++++++++++++++ Grading $name... +++++++++++++++++++++++"
  ./grade io/ "$f" "$2/$name"
done

